### ISSUE TITLE
DaveGut

### ISSUE THREAD

**Issue by ramiran2** [DaveGut/SmartThings_Cloud-Based_TP-Link-Plugs-Switches-Bulbs#19]
Hello, I have been working on this project for some time and it's almost done. I don't claim to be the best coder but for some reason, I decided to work on your project. I know for a fact that I don't fully understand the syntax of this language but with plenty of testing, I have made a lot of chances. I got SmartThings about 1-2 months ago so... I hope you don't take this the wrong way. Maybe sometime we can compare notes?
I have changed the UI
Added Support for the new SmartThings App
Added a login page
Added Device Health
Changes the naming on the drivers
Etc...
https://github.com/ramiran2/TP-Link-SmartThings

**Comment by DaveGut** [comment]
I do not take it the wrong way.  Looking at your code, I have a few questions; however, I would like to check out on classic first.  It does look like an improvement.

Does it work with the new app?????

If this works out, I woul like to integrate into SmartThings with credit to you for your guidance, advice, and improved coding.

Dave

**Comment by ramiran2** [comment]
so far yes I actually use it but maybe more testing is needed. I'm only one person and the amount of code that was add well. Well go ahead and test it all out something to note the icons may need changing.

**Comment by ramiran2** [comment]
it's ok to take your time until I find a bug I will not be adding much more anyways

**Comment by ramiran2** [comment]
If you need to contact me ramiran4@gmail.com and we can go from there

**Comment by DaveGut** [comment]
Good.  Let me play a bit.  Need to set some debug points and see what is happening.



Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by ramiran2** [comment]
hey I can't believe I'm still working on this but I'm working on a big update that makes my old ui a joke with less issue :D

**Comment by uSlackr** [comment]
How do we update our installs?

\\\\Greg

________________________________

**Comment by ramiran2** [comment]
Did you try removing the old app then going to SmartThings ide and manually copying the new code into the old app location (My SmartApps) remember you need to replace the old code. you will also have to do that for each device hander too (My Device Handlers)

**Comment by uSlackr** [comment]
Hadn’t tried anything. Wasn’t sure the process. Thank you!

\\\\Greg

________________________________

**Comment by ramiran2** [comment]
Hey DaveGut i think i just finished 3.5.0 go head and test to see if you have better luck with this 1182 line of code

**Comment by DaveGut** [comment]
Will do tomorrow.  Thanks.



Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by ramiran2** [comment]
Depending on what you do I will change my version of the device handlers. example a simpler device health check. Note I would like to see you split the device handler of plug and switch into two so the icon can match the device in SmartThings. That is why i did that

**Comment by DaveGut** [comment]
I will break the Switch from the Plug.  I agree – especially with the new App.

Finding some concerns in the SmartApp.  Still examining (I LIKE IT).  Login works great and the interface is great.


  1.  Major:  Devices are not installing.  Added log.debug statements.  Not getting to addDevices.  Save does not go to addDevices.

Did the below change and fixed add devices.  Also remove devices work.

def initialize() {

            unsubscribe()

            unschedule()

            runEvery5Minutes(checkError)

            schedule("0 30 2 ? * WED", getToken)

//          if (selectedDevices) {

//                      if (userSelectedRemoveMode){

//                                  removeDevices()

//                      } else {

//                                  addDevices()

//                      }

//          }

            if (userSelectedDevicesRemove) removeDevices()

           if (userSelectedDevicesAdd) addDevices()

}

  1.  Minor:  Currently, the app causes a new token whenever you visit the selectDevices page.  Caused by the value of userSelectedOptionTwo =~ "Activate Account".  Never changed after the account is activated.  Causes unnecessary ping of the Kasa site – but not a lot – so acceptable.



  1.  NIT:  System runs another getDevices() when finishing the select process.  Do not know why, but is really a nit.



  1.  Minor:  Not currently sending data to the devices for Transition Time and refresh rate.  I will look at adding code to set these when installing new devices.  Will require DH as well as SmartApp code!

Thanks for the good work.  The SmartApp is much better.  Was wondering on how to set the options in the new app.  If that works, it will solve that problem.  Also the device removal.   GOOD ADDS – especially given the limits of the SmartThings App.

When done, I would like to create a production version.  Would not have developer sections.  Need to also determine if versioning is necessary (there is nothing in your SmartApp that would preclude use of the existing drivers other than the file names).  Would list author as you and me (ala what I did for the Device Handlers).  Would be good to be backward compatible for user simplicity.

Dave

**Comment by DaveGut** [comment]
Instructions are on the GITHUB as well as SmartThings forum.

**Comment by ramiran2** [comment]
Ya i know i was working on the fix when i was testing it :D

**Comment by ramiran2** [comment]
NIT: System runs another getDevices() when finishing the select process. Do not know why, but is really a nit. This is due to Do you want to enable recommended options?
 1. Minor: Not currently sending data to the devices for Transition Time and refresh rate. I will look at adding code to set these when installing new devices. Will require DH as well as SmartApp code!
i have not add the code to the device handlers but the smart app is ready i think as it should send the string just the device handlers don't have anything to do with them

**Comment by ramiran2** [comment]
hey, do you if there is any way that I can request a page to reload? without user input?

**Comment by ramiran2** [comment]
hey update 3.5.0 is 99% complete so test it should results the best the one small bug is you have to go and reload the settings page if you enable recommend options

**Comment by ramiran2** [comment]
you have no idea how many days I spent up late. i mean you have to know with the amount of progress I have done in so little time. none the less I hope you like version 3.5.0

**Comment by DaveGut** [comment]
Really like the version.  If you want, I can do the recommendations below and get it back to you with full documentation on the changes made internal.  Up to you - THIS IS A GOOD PROGRAM as is.  One fix absolutely needed:  On the device preferences, do not require that these fields be populated (required false).  

Some point recommendations.
1.  What do you want to do?
     a.  Add "Set Device Preferences".  (Will discuss this later.)
     b.  Create "Add Devices" and "Remove Devices" as separate options.
     c.  Cosmetic:  Reorder Options: Add, Delete, Preferences, Update Token, Initial Installation.
2.  Instead of reloading on selection of an option, create a single page (instead of Device Manager Page, etc).  This would
     a.  Title:  Continue with Selection
     b.  Would jump to the appropriate page.
3.  Do you want to enable recommend options?  Delete.  Would be in Preferences.
     a.  Would use the same list as the delete devices page.
     b.  User would Select Devices for the options to apply.
     c.  Options as currently coded; however, no entry required.
4.  Preferences
     a.  New page.  Uses same data as the current delete devices.
     b.  User selects the devices to apply preferences to.
     c.   User fills in the values and selects save
     d.  Updates done on the selected devices.  (two commands to each device.  Dummy command for plugs / switches for transition time,)

**Comment by DaveGut** [comment]
I get like that also.  Usually, go to sleep at 11, wake up at 2:30 because I have to solve the puzzle.

BTW.  These DHs were my first ever software projects.   That and the Samsung Multiroom speaker items are my legacy to SmartThings.  I will be 70 in 2 months, so kind of old to learn new tricks - BUT YOU HAVE TAUGHT ME NEW TRICKS.

Dave

**Comment by ramiran2** [comment]
ok will do

**Comment by DaveGut** [comment]
**Setting device preferences**
See attached zip files.  They contain changes to **def updated()** plus two new functions at the bottom of the page.  Slightly different for the plugs/switches than the bulbs.

[TPLink Devices.zip](https://github.com/DaveGut/SmartThings_Cloud-Based_TP-Link-Plugs-Switches-Bulbs/files/2476755/TPLink.Devices.zip)

**SmartApp Code**
The Smart App/Service Manager function is below.  This will update all installed devices!
def setDefaultPreferences() {
	def currentDevices = getDeviceData()
	currentDevices.each {
 		def isChild = getChildDevice(it.deviceMac)
		if (isChild) {
			isChild.setLightTransTime(userLightTransTime)
			isChild.setRefreshRate(userRefreshRate)
		}
		log.info "Device ${it.alias} added to devices array"
	}
}

**Comment by ramiran2** [comment]
Thank you i just notice so errors I made and am fixing the device handlers

**Comment by DaveGut** [comment]
I have finished my versions of the handlers.  Getting ready to test.  They have the capability updates from SmartThings.  For plugs/switches, three files (plug, switch, switch with level).  Single file for maintenance.

**Comment by ramiran2** [comment]
i hope it goes well but maybe consider GitHub integration with SmartThings to make it easy for users to install from the repo

**Comment by DaveGut** [comment]
Already have it.  Issue is not all the users have it, so I have to maintain the GitHub repository.  GitHub link is djgut

**Comment by ramiran2** [comment]
https://desktop.github.com/? i only ask because well this is my first project on GitHub so if you did not know this exists then :)

**Comment by DaveGut** [comment]
No. Thanks for thinking of me.  That is the way I took it



Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by ramiran2** [comment]
} else if (cmdResponse[state.emeterText].err_code == -1) {
		log.error "${device.name} ${device.label}: does not support Energy Monitor.  Energy Monitor disabled."
		state.emon == "Standard" (Is this not supposed to be state.emon = "Standard")
		unschedule(getEnergyStats)

**Comment by DaveGut** [comment]
It is legacy from when I had the energy monitor in the same file as others.  I will remove from my driver on SmartThings and in the future on GitHub.

Dave

**Comment by ramiran2** [comment]
Status update SmartThings App redesign 80% 
This update will really be a cool one i can't wait for it to be done :D

**Comment by ramiran2** [comment]
If you are interested you can see the progress on 3.6.0 :)

**Comment by DaveGut** [comment]
Will look tonite.



Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by ramiran2** [comment]
Update 3.6.0 Done

**Comment by ramiran2** [comment]
hey I think I have an idea for that but man it will take time :(

**Comment by DaveGut** [comment]
Collaboration in progress.
